### ISSUE TITLE
-tao-fd does not work for hessian

### ISSUE THREAD

**Issue by jtilly** [jtilly/taoR#10]
Cannot compute the hessian using finite differences. In principle, using the option `-tao-fd` should turn on finite differences for the hessian by invoking [TaoDefaultComputeHessian](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Tao/TaoDefaultComputeHessian.html). For some reason that doesn't work. Not even if I hard-code `TaoDefaultComputeHessian` into the C++ code. For now, I turned off finite differences for hessians in [tao.R](https://github.com/jtilly/taoR/blob/master/R/tao.R#L105).

Interestingly, using finite differences for the gradient computation using the option `-tao_fd_gradient` works like a charm.

**Comment by njanetos** [comment]
Where is the documentation for tao fd computing the hessian?

**Comment by njanetos** [comment]
Its not `-tao_fd_hessian`?

**Comment by jtilly** [comment]
Documentation is here:
http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Tao/TaoDefaultComputeHessian.html
and here http://www.mcs.anl.gov/petsc/petsc-current/docs/tao_manual.pdf on
page 15.

**Comment by njanetos** [comment]
Well I'm trying to compile petsc so detective nick can't currently investigate the Mystery of the Missing Hessian but I do notice that there appears to be a routine, `TAOTEST`, that just compares hessians and gradients computed with finite differences to the user-supplied ones. It might be worthwhile at some point to actually wrap that separately in `tao.R`.

**Comment by jtilly** [comment]
I don't think `-tao-fd` is actually implemented in PETSc. It only exists in the documentation, not in the source code. Computing a Hessian with finite differences is a bad idea anyways. The only example that uses `TaoDefaultComputeHessian` is [minsurf2.c](http://www.mcs.anl.gov/petsc/petsc-current/src/tao/unconstrained/examples/tutorials/minsurf2.c.html). However, this example uses [taocg](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Tao/TAOCG.html#TAOCG), an algorithm that doesn't need (or use) a Hessian in the first place.

**Comment by njanetos** [comment]
In that case, I'm going to close this issue, and taoR won't have support for numerical Hessians.
