### ISSUE TITLE
Windows petsc binaries

### ISSUE THREAD

**Issue by njanetos** [jtilly/taoR#21]
Need to compile them on windows (32bit and 64bit?) and then add a `Makevars.win` file to download them if no petsc installation is found.

**Comment by jtilly** [comment]
I'm just taking a look at how to compile the binaries with a `configure.win` script.

**Comment by njanetos** [comment]
Reminder me which one you think CRAN wouldn't be happy with -- precompiled binaries, or downloading the source code and compiling it with the package?

**Comment by jtilly** [comment]
There are packages that come with precompiled binaries -- so I think that's okay. However, these precompiled binaries should actually work on all systems and not just if you're lucky.

**Comment by njanetos** [comment]
Petsc is building. I'll look at your configure.win thingy.

**Comment by njanetos** [comment]
How are you testing this? Did you get your hands on a windows computer?

**Comment by jtilly** [comment]
Found an old Windows laptop that takes about 10 minutes to extract the petsc tar ball.
