### ISSUE TITLE
Variable names

### ISSUE THREAD

**Issue by njanetos** [jtilly/taoR#7]
We should refactor the code at some point so it uses variable names consistent with C++ style conventions. I.e., even if we still use camelCase instead of underlines, the first letter in function names should be lowercase. Also why aren't we using `namespace std` and `namespace Rcpp`.

**Comment by njanetos** [comment]
Further on that the default `PETSc` examples are hard to read and things like `ierr` should probably be renamed to be more readable.

**Comment by jtilly** [comment]
Sounds good. You can use `namespace std` and `namespace Rcpp`. I didn't use them to begin with to avoid stupid mistakes.

**Comment by njanetos** [comment]
Changed in #9
